<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ErrorHandlingService\Service'                    => __DIR__ . '/src/ErrorHandlingService/Service/ErrorHandlingService.php',
);