<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Abstracts\Model'                    => __DIR__ . '/src/Abstracts/Model/AbstractBaseModel.php',
	'Abstracts\Model'                    => __DIR__ . '/src/Abstracts/Model/AbstractRESTModule.php',
);